// TOPIC
export const SEGMENT_SEARCH = 'TOPIC_SEARCH';
export const SEGMENT_INSERT = 'TOPIC_INSERT';
export const SEGMENT_UPDATE = 'TOPIC_UPDATE';
export const SEGMENT_DELETE = 'TOPIC_DELETE';
export const SEGMENT_APPROVE = 'TOPIC_APPROVE';
export const SEGMENT_SEARCH_BY_ID = 'TOPIC_SEARCH_BY_ID';