// SEGMENT
export const SEGMENT_SEARCH = 'SEGMENT_SEARCH';
export const SEGMENT_INSERT = 'SEGMENT_INSERT';
export const SEGMENT_UPDATE = 'SEGMENT_UPDATE';
export const SEGMENT_DELETE = 'SEGMENT_DELETE';
export const SEGMENT_APPROVE = 'SEGMENT_APPROVE';
export const SEGMENT_SEARCH_BY_ID = 'SEGMENT_SEARCH_BY_ID';
export const SEGMENT_PAGE = 'SEGMENT_PAGE';

export const SIGN_OUT = 'SIGN_OUT';