// RULES
export const RULES_SEARCH = 'RULES_SEARCH';
export const RULES_INSERT = 'RULES_INSERT';
export const RULES_UPDATE = 'RULES_UPDATE';
export const RULES_DELETE = 'RULES_DELETE';
export const RULES_APPROVE = 'RULES_APPROVE';
export const RULES_SEARCH_BY_ID = 'RULES_SEARCH_BY_ID';
export const RULES_WHEEL_APPROVED = 'RULES_WHEEL_APPROVED';
export const RULES_WHEEL_DETAIL = 'RULES_WHEEL_DETAIL';
export const RULES_WHEEL = 'RULES_WHEEL';
export const RULES_STATE_YES = 'RULES_STATE_YES';