// TOPIC
export const WHEELDETAIL_SEARCH = 'WHEELDETAIL_SEARCH';
export const WHEELDETAIL_INSERT = 'WHEELDETAIL_INSERT';
export const WHEELDETAIL_UPDATE = 'WHEELDETAIL_UPDATE';
export const WHEELDETAIL_DELETE = 'WHEELDETAIL_DELETE';
export const WHEELDETAIL_APPROVE = 'WHEELDETAIL_APPROVE';
export const WHEELDETAIL_SEARCH_BY_ID = 'WHEELDETAIL_SEARCH_BY_ID';
