// MANAGER_DETAIL_CB
export const MANAGER_DETAIL_CB_COIN_SEARCH = 'MANAGER_DETAIL_CB_SEARCH';
export const MANAGER_DETAIL_CB_INSERT = 'MANAGER_DETAIL_CB_INSERT';
export const MANAGER_DETAIL_CB_UPDATE = 'MANAGER_DETAIL_CB_UPDATE';
export const MANAGER_DETAIL_CB_DELETE = 'MANAGER_DETAIL_CB_DELETE';
export const MANAGER_DETAIL_CB_APPROVE = 'MANAGER_DETAIL_CB_APPROVE';
export const MANAGER_DETAIL_CB_SEARCH_BY_ID = 'MANAGER_DETAIL_CB_SEARCH_BY_ID';