// TOPIC
export const TOPIC_SEARCH = 'TOPIC_SEARCH';
export const TOPIC_SEARCH_COMMON = 'TOPIC_SEARCH_COMMON';
export const TOPIC_INSERT = 'TOPIC_INSERT';
export const TOPIC_UPDATE = 'TOPIC_UPDATE';
export const TOPIC_DELETE = 'TOPIC_DELETE';
export const TOPIC_APPROVE = 'TOPIC_APPROVE';
export const TOPIC_SEARCH_BY_ID = 'TOPIC_SEARCH_BY_ID';
export const TOPIC_PAGE = 'TOPIC_PAGE';

export const SIGN_OUT = 'SIGN_OUT';