// MANAGER_CB_COIN
export const MANAGER_CB_COIN_SEARCH = 'MANAGER_CB_COIN_SEARCH';
export const MANAGER_CB_COIN_INSERT = 'MANAGER_CB_COIN_INSERT';
export const MANAGER_CB_COIN_UPDATE = 'MANAGER_CB_COIN_UPDATE';
export const MANAGER_CB_COIN_DELETE = 'MANAGER_CB_COIN_DELETE';
export const MANAGER_CB_COIN_APPROVE = 'MANAGER_CB_COIN_APPROVE';
export const MANAGER_CB_COIN_SEARCH_BY_ID = 'MANAGER_CB_COIN_SEARCH_BY_ID';


export const SIGN_OUT = 'SIGN_OUT';