export const WHEELPOPUPMENU_REWARD_SEARCH ='WHEELPOPUPMENU_REWARD_SEARCH';
export const WHEELPOPUPMENU_WHEELDETAILBYID_SEARCH ='WHEELPOPUPMENU_WHEELDETAILBYID_SEARCH';
export const WHEELPOPUPMENU_CUSTOMER_SEARCH ='WHEELPOPUPMENU_CUSTOMER_SEARCH';
export const WHEELPOPUPMENU_SEARCHALL='WHEELPOPUPMENU_SEARCHALL';

export const SIGN_OUT = 'SIGN_OUT';